version: 2.1

executors:
    docker-executor:
        docker:
            - image: circleci/node:14.2.0

commands:
    install-libs:
        description: "Command to modules synchronization"
        steps:
            - run:
                name: Modules synchronization
                command: npm install

jobs:
    check-environment:
        executor: docker-executor
        steps:
            - checkout
            - run:
                name: Check modules
                command: |
                    npm -v
    test:
        executor: docker-executor
        steps:
            - checkout
            - restore_cache:
                key: test-libs-{{ .Branch }}-{{ checksum "package.json" }}
            - install-libs
            - save_cache:
                key: test-libs-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - "node_modules"
            - run:
                name: Run tests
                command: npm test
    build-release:
        executor: docker-executor
        steps:
            - checkout
            - restore_cache:
                key: build-libs-{{ .Branch }}-{{ checksum "package.json" }}
            - install-libs
            - save_cache:
                key: build-libs-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - "node_modules"
            - run:
                name: Building
                command: npm run prod
            - run:
                name: Result build
                command: ls -la ./prod
            - run:
                name: Add routing
                command: echo "/*    /index.html  200" > ./dist/_redirects
            - persist_to_workspace:
                root: .
                paths:
                    - dist
    deploy-release:
        executor: docker-executor
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: Install netlify cli
                command: sudo npm install -g --silent netlify-cli
            - run:
                name: Deploy to netlify service
                command: netlify deploy --dir=./dist -p

workflows:
    testing:
        jobs:
            - check-environment
            # - test
            - approve-build:
                type: approval
                # requires:
                #     - test
                filters:
                    branches:
                        only: develop
            - build-release:
                requires:
                    - approve-build
                filters:
                    branches:
                        only: develop
            - approve-deploy:
                type: approval
                requires:
                    - build-release
                filters:
                    branches:
                        only: develop
            - deploy-release:
                requires:
                    - approve-deploy
                filters:
                    branches:
                        only: develop
